sudo: required

services:
  - docker

before_install:
  - docker --version

language: python

script:
  - docker --version
  - docker-compose --version
  - cd docker-images/aa-server/
  - ./build-docker-image.sh
  - cd ../aa-unittest/
  - ./build-docker-image.sh
  - cd ../../docker-topologies/runtime
  - docker-compose up -d
  - cd ../../docker-images/aa-unittest/
  - ./run-docker-image.sh
  - cd ../../docker-topologies/runtime
  - docker-compose down
